FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY apps/backend .
RUN ./mvnw -pl onehealth-api -am package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/onehealth-api/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
